import React from 'react'
import './globals.css'
import NavBar from './components/NavBar';

export const metadata = {
    description: 'Generated by Next.js',
    title: 'Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="nl">

            <body>
                <div className="h-auto">
                    {children}
                </div>
            </body>

        </html>
    )
}